// testbench generated by chatgpt
`timescale 1ns / 1ps

module alu_tb;

    reg  [63:0] a;
    reg  [63:0] b;
    reg  [3:0]  opcode;
    wire [63:0] result;

    // DUT instance
    alu dut (
        .a(a),
        .b(b),
        .opcode(opcode),
        .result(result)
    );

    task run_test;
        input [63:0] ta;
        input [63:0] tb;
        input [3:0]  topcode;
        input [255:0] name;
    begin
        a      = ta;
        b      = tb;
        opcode = topcode;
        #5; // allow combinational settle
        $display("[%0t] %s: opcode=%b a=%h b=%h -> result=%h",
                 $time, name, opcode, a, b, result);
    end
    endtask

    initial begin
        $display("Starting ALU SIMD 4x16 testbench");

        // Basic AND
        run_test(64'hFFFF_0000_F0F0_1234,
                 64'h0F0F_FFFF_00FF_FFFF,
                 4'b0000,
                 "AND lanes");

        // Basic OR
        run_test(64'h0000_F0F0_0000_1234,
                 64'h0F0F_0000_FFFF_0000,
                 4'b0001,
                 "OR lanes");

        // SUM: per-lane 16-bit adds
        // lane values: a: [1, 2, 3, 4], b: [10, 20, 30, 40]
        run_test({16'd4, 16'd3, 16'd2, 16'd1},
                 {16'd40, 16'd30, 16'd20, 16'd10},
                 4'b0010,
                 "SUM lanes");

        // SUM: check wrap-around within lane (0xFFFF + 1 -> 0x0000)
        run_test({16'hFFFF, 16'h0001, 16'h8000, 16'h7FFF},
                 {16'h0001, 16'hFFFF, 16'h0001, 16'h0001},
                 4'b0010,
                 "SUM wrap lanes");

        // SUB: per-lane 16-bit subs
        run_test({16'd100, 16'd50, 16'd0, 16'd1},
                 {16'd90,  16'd10, 16'd1, 16'd2},
                 4'b0011,
                 "SUB lanes");

        // XNOR
        run_test(64'hFFFF_0000_A5A5_5A5A,
                 64'h0F0F_F0F0_5A5A_A5A5,
                 4'b0100,
                 "XNOR lanes");

        // CMP signed: lanes with mixed sign
        // a lanes: [-1, -2, 3, 4], b lanes: [0, -2, 2, 5]
        run_test({$signed(16'sd4),  $signed(16'sd3),
                  $signed(-16'sd2), $signed(-16'sd1)},
                 {$signed(16'sd5),  $signed(16'sd2),
                  $signed(-16'sd2), $signed(16'sd0)},
                 4'b0101,
                 "CMP signed lanes");

        // MOV
        run_test(64'hDEAD_BEEF_1234_5678,
                 64'hFEDC_BA98_7654_3210,
                 4'b0111,
                 "MOV lanes");

        $display("ALU SIMD 4x16 testbench complete");
        $finish;
    end

endmodule