// testbench generated by chatgpt
`timescale 1ns / 1ps

module tb_control_unit;

    // --------------------------
    // Clock / Reset
    // --------------------------
    reg clk;
    reg reset;

    always #5 clk = ~clk;   // 10ns period

    // --------------------------
    // Decoder inputs
    // --------------------------
    reg [3:0]  rd;
    reg [3:0]  rs1;
    reg [3:0]  rs2;
    reg [13:0] imm;
    reg [3:0]  alu_opcode;
    reg        regfile_we_dec;
    reg        alu_enable_dec;
    reg        mem_read_dec;
    reg        mem_write_dec;
    reg        tensor_start_dec;
    reg        stall_cpu_dec;

    // --------------------------
    // Data inputs (fake sources)
    // --------------------------
    reg [63:0] alu_result;
    reg [63:0] regfile_douta;
    reg [63:0] regfile_doutb;
    reg [63:0] mem_read_data;
    reg        tensor_done;
    reg [63:0] tensor_result;

    // --------------------------
    // Outputs
    // --------------------------
    wire [1:0]  regfile_raddr_a;
    wire [1:0]  regfile_raddr_b;
    wire [1:0]  regfile_waddr;
    wire        regfile_we;
    wire [63:0] regfile_wdata;

    wire [31:0] mem_addr;
    wire [63:0] mem_wdata;
    wire        mem_we;

    wire        tensor_go;

    // --------------------------
    // DUT
    // --------------------------
    control_unit DUT (
        .clk(clk),
        .reset(reset),

        .rd(rd),
        .rs1(rs1),
        .rs2(rs2),
        .imm(imm),
        .alu_opcode(alu_opcode),
        .regfile_we_dec(regfile_we_dec),
        .alu_enable_dec(alu_enable_dec),
        .mem_read_dec(mem_read_dec),
        .mem_write_dec(mem_write_dec),
        .tensor_start_dec(tensor_start_dec),
        .stall_cpu_dec(stall_cpu_dec),

        .alu_result(alu_result),
        .regfile_douta(regfile_douta),
        .regfile_doutb(regfile_doutb),
        .mem_read_data(mem_read_data),
        .tensor_done(tensor_done),
        .tensor_result(tensor_result),

        .regfile_raddr_a(regfile_raddr_a),
        .regfile_raddr_b(regfile_raddr_b),
        .regfile_waddr(regfile_waddr),
        .regfile_we(regfile_we),
        .regfile_wdata(regfile_wdata),

        .mem_addr(mem_addr),
        .mem_wdata(mem_wdata),
        .mem_we(mem_we),

        .tensor_go(tensor_go)
    );

    // --------------------------
    // TEST SEQUENCE
    // --------------------------
    initial begin
        $display("==== Starting Control Unit Test ====");

        clk = 0;
        reset = 1;

        // Clear all inputs
        rd = 0; rs1 = 0; rs2 = 0; imm = 0;
        alu_opcode = 0;
        regfile_we_dec = 0;
        alu_enable_dec = 0;
        mem_read_dec = 0;
        mem_write_dec = 0;
        tensor_start_dec = 0;
        stall_cpu_dec = 0;
        alu_result = 0;
        regfile_douta = 0;
        regfile_doutb = 0;
        mem_read_data = 0;
        tensor_done = 0;
        tensor_result = 0;

        #20;
        reset = 0;

        //------------------------------------------------------------
        // TEST 1: ALU WRITEBACK
        //------------------------------------------------------------
        #20;
        $display("Testing ALU writeback...");

        rd = 4'b0011;   // R3
        alu_enable_dec = 1;
        regfile_we_dec = 1;
        alu_result = 64'hDEADBEEFCAFEBABE;

        #10;

        if (regfile_we !== 1)
            $display("FAIL: ALU write enable not asserted");
        else if (regfile_wdata !== 64'hDEADBEEFCAFEBABE)
            $display("FAIL: ALU write data incorrect");
        else
            $display("PASS: ALU writeback");

        alu_enable_dec = 0;
        regfile_we_dec = 0;

        //------------------------------------------------------------
        // TEST 2: MEMORY STORE
        //------------------------------------------------------------
        #20;
        $display("Testing Memory Store...");

        mem_write_dec = 1;
        regfile_douta = 64'h0000000000001000;  // address
        regfile_doutb = 64'hFACEFACEFACEFACE;  // data

        #10;

        if (mem_we !== 1)
            $display("FAIL: mem_we not asserted");
        else if (mem_wdata !== 64'hFACEFACEFACEFACE)
            $display("FAIL: mem_wdata incorrect");
        else
            $display("PASS: Memory Store");

        mem_write_dec = 0;

        //------------------------------------------------------------
        // TEST 3: MEMORY LOAD
        //------------------------------------------------------------
        #20;
        $display("Testing Memory Load...");

        rd = 4'b0001;   // R1
        mem_read_dec = 1;
        regfile_douta = 64'h0000000000002000;

        #10;
        mem_read_dec = 0;

        // simulate memory returning data next cycle
        mem_read_data = 64'h123456789ABCDEF0;

        #10;

        if (regfile_we !== 1)
            $display("FAIL: LD write enable not asserted");
        else if (regfile_wdata !== 64'h123456789ABCDEF0)
            $display("FAIL: LD write data incorrect");
        else
            $display("PASS: Memory Load");

        //------------------------------------------------------------
        // TEST 4: TENSOR START + DONE
        //------------------------------------------------------------
        #20;
        $display("Testing Tensor...");

        rd = 4'b0010;  // R2
        tensor_start_dec = 1;

        #10;
        tensor_start_dec = 0;

        if (tensor_go !== 1)
            $display("FAIL: tensor_go not asserted");
        else
            $display("PASS: Tensor start");

        // simulate tensor finishing
        #20;
        tensor_done = 1;
        tensor_result = 64'hAAAAAAAAAAAAAAAA;

        #10;
        tensor_done = 0;

        if (regfile_wdata !== 64'hAAAAAAAAAAAAAAAA)
            $display("FAIL: Tensor writeback incorrect");
        else
            $display("PASS: Tensor writeback");

        //------------------------------------------------------------
        #50;
        $display("==== Control Unit Test Complete ====");
        $finish;
    end

endmodule