// testbench generated by chatgpt
`timescale 1ns / 1ps

module tb_decoder;

    reg  [31:0] instr;
    reg         tensor_busy;

    wire [3:0]  rd;
    wire [3:0]  rs1;
    wire [3:0]  rs2;
    wire [13:0] imm;

    wire [3:0]  alu_opcode;
    wire        regfile_we;
    wire        alu_enable;
    wire        mem_read;
    wire        mem_write;
    wire        tensor_start;
    wire        stall_cpu;

    // Instantiate DUT
    decoder DUT (
        .instr(instr),
        .tensor_busy(tensor_busy),

        .rd(rd),
        .rs1(rs1),
        .rs2(rs2),
        .imm(imm),

        .alu_opcode(alu_opcode),
        .regfile_we(regfile_we),
        .alu_enable(alu_enable),
        .mem_read(mem_read),
        .mem_write(mem_write),
        .tensor_start(tensor_start),
        .stall_cpu(stall_cpu)
    );

    // Helper task to build instruction
    task build_instr;
        input [1:0] type;
        input [3:0] op;
        input [3:0] rd_i;
        input [3:0] rs1_i;
        input [3:0] rs2_i;
        input [13:0] imm_i;
        begin
            instr = {type, op, rd_i, rs1_i, rs2_i, imm_i};
        end
    endtask

    initial begin
        $display("==== Starting Decoder Test ====");
        tensor_busy = 0;

        //---------------------------------------
        // TEST 1: ALU (type=00, op=SUM=0010)
        //---------------------------------------
        build_instr(2'b00, 4'b0010, 4'h3, 4'h1, 4'h2, 14'h0001);
        #1;

        if (!alu_enable || !regfile_we || alu_opcode != 4'b0010)
            $display("FAIL: ALU decode");
        else
            $display("PASS: ALU decode");

        //---------------------------------------
        // TEST 2: LD (type=01, op=0000)
        //---------------------------------------
        build_instr(2'b01, 4'b0000, 4'h2, 4'h1, 4'h0, 14'h0000);
        #1;

        if (!mem_read || !regfile_we)
            $display("FAIL: LD decode");
        else
            $display("PASS: LD decode");

        //---------------------------------------
        // TEST 3: ST (type=01, op=0001)
        //---------------------------------------
        build_instr(2'b01, 4'b0001, 4'h2, 4'h1, 4'h3, 14'h0000);
        #1;

        if (!mem_write || regfile_we)
            $display("FAIL: ST decode");
        else
            $display("PASS: ST decode");

        //---------------------------------------
        // TEST 4: BF16_MUL (type=10, op=0000)
        //---------------------------------------
        build_instr(2'b10, 4'b0000, 4'h1, 4'h2, 4'h3, 14'h0000);
        #1;

        if (!alu_enable || !regfile_we)
            $display("FAIL: BF16_MUL decode");
        else
            $display("PASS: BF16_MUL decode");

        //---------------------------------------
        // TEST 5: FMA (type=10, op=0001)
        //---------------------------------------
        build_instr(2'b10, 4'b0001, 4'h1, 4'h2, 4'h3, 14'h0000);
        #1;

        if (!tensor_start || !stall_cpu)
            $display("FAIL: FMA decode");
        else
            $display("PASS: FMA decode");

        //---------------------------------------
        // TEST 6: RELU (type=10, op=0010)
        //---------------------------------------
        build_instr(2'b10, 4'b0010, 4'h1, 4'h2, 4'h3, 14'h0000);
        #1;

        if (!alu_enable || !regfile_we)
            $display("FAIL: RELU decode");
        else
            $display("PASS: RELU decode");

        //---------------------------------------
        // TEST 7: TENSOR_DOT (type=10, op=0011)
        //---------------------------------------
        build_instr(2'b10, 4'b0011, 4'h1, 4'h2, 4'h3, 14'h0000);
        #1;

        if (!tensor_start || !stall_cpu)
            $display("FAIL: TENSOR_DOT decode");
        else
            $display("PASS: TENSOR_DOT decode");

        //---------------------------------------
        // TEST 8: CVTA (type=11, op=0000)
        //---------------------------------------
        build_instr(2'b11, 4'b0000, 4'h1, 4'h2, 4'h3, 14'h0000);
        #1;

        if (!alu_enable || !regfile_we)
            $display("FAIL: CVTA decode");
        else
            $display("PASS: CVTA decode");

        //---------------------------------------
        // TEST 9: tensor_busy forces stall
        //---------------------------------------
        tensor_busy = 1;
        build_instr(2'b00, 4'b0010, 4'h1, 4'h2, 4'h3, 14'h0000);
        #1;

        if (!stall_cpu)
            $display("FAIL: tensor_busy stall");
        else
            $display("PASS: tensor_busy stall");

        tensor_busy = 0;

        //---------------------------------------
        // TEST 10: Field extraction check
        //---------------------------------------
        build_instr(2'b00, 4'b0001, 4'hA, 4'hB, 4'hC, 14'h1234);
        #1;

        if (rd != 4'hA || rs1 != 4'hB || rs2 != 4'hC || imm != 14'h1234)
            $display("FAIL: Field extraction");
        else
            $display("PASS: Field extraction");

        //---------------------------------------
        $display("==== Decoder Test Complete ====");
        $finish;
    end

endmodule